name: Label PR

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write

jobs:
  label-pr:
    uses: ecmwf/reusable-workflows/.github/workflows/label-pr.yml@main
